### ISSUE TITLE
Cannot initialize model

### ISSUE THREAD

**Issue by yian-yin** [PythonCharmers/maxentropy#5]
Hi there,

I was trying to run the examples but got stuck at the very beginning, showing 
Traceback (most recent call last):
  File "berger_example.py", line 43, in <module>
    model = maxentropy.Model(f, samplespace)
  File "/Users/yianyin/anaconda/lib/python3.6/site-packages/maxentropy-0.2.3-py3.6.egg/maxentropy/model.py", line 53, in __init__
    super(Model, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'prior_log_probs'

Anyone has ideas what's going on? Thanks a lot!

**Comment by edschofield** [comment]
Sorry, you got caught in the middle of refactoring.

Fixed in the latest version (0.3.0).
